### ISSUE TITLE
Changing backlight color?

### ISSUE THREAD

**Issue by ewosborne** [donfeduardo/Kaleidoscope-CapsLock#1]
The backlight color is hard coded in the .cpp file as

`cRGB activeModeColor = CRGB(255, 0, 0);`

It would be cool to make two small changes:

1) change the red to 160, 0, 0; per the firmware .ino file, that value is calibrated for minimal power draw.

2) move the color definition outside of the .cpp file and into the .ino file so that the user can change it without touching the .cpp file. It may be possible to do this already but I couldn't figure out how. I tried `static kaleidoscope::activeModeColor &solidViolet;`  but no dice. I could spend an hour figuring it out, or hope that it'll take you like twelve seconds to do.

Thanks!

**Comment by donfeduardo** [comment]
I had pondered whether anybody would want that, but figured I could wait until somebody asked or submitted a PR. I'll take a look.

**Comment by donfeduardo** [comment]
This has been added to the new version of the plugin, but the new version of the plugin requires the new plugin architecture in the latest version of Kaleidoscope, so you'll have to update your whole repo in order to get the new configurability.
